"""add_searchable_text_and_gin_index

Revision ID: 35fc9a73097a
Revises: 80d7765a9d83
Create Date: 2026-09-16 11:56:24.084587

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35fc9a73097a"
down_revision: str | Sequence[str] | None = "80d7765a9d83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column(
            "searchable_text",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', text)", persisted=True),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_document_chunks_searchable_text",
        "document_chunks",
        ["searchable_text"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_document_chunks_searchable_text", table_name="document_chunks", postgresql_using="gin"
    )
    op.drop_column("document_chunks", "searchable_text")
    # ### end Alembic commands ###
