"""add_vector_embeddings_and_indexing_status

Revision ID: 80d7765a9d83
Revises: 176dc861a77e
Create Date: 2026-09-16 11:21:20.507263

"""

from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80d7765a9d83"
down_revision: str | Sequence[str] | None = "176dc861a77e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    indexing_status_enum = postgresql.ENUM(
        "PENDING", "PROCESSING", "COMPLETED", "FAILED", name="indexing_status", create_type=False
    )
    indexing_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "document_chunks",
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    )
    op.add_column(
        "documents",
        sa.Column(
            "indexing_status",
            indexing_status_enum,
            server_default="PENDING",
            nullable=False,
        ),
    )
    op.add_column("documents", sa.Column("indexing_error", sa.Text(), nullable=True))
    op.add_column("documents", sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        op.f("ix_documents_indexing_status"), "documents", ["indexing_status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_indexing_status"), table_name="documents")
    op.drop_column("documents", "indexed_at")
    op.drop_column("documents", "indexing_error")
    op.drop_column("documents", "indexing_status")
    op.drop_column("document_chunks", "embedding")
    # ### end Alembic commands ###
