"""add_indexing_jobs_and_admin_rbac

Revision ID: aab1529830b5
Revises: d4e5f6a7b8c9
Create Date: 2026-09-23 11:48:04.443708

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aab1529830b5"
down_revision: str | Sequence[str] | None = "d4e5f6a7b8c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indexing_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_base_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("total_chunks", sa.Integer(), nullable=False),
        sa.Column("processed_chunks", sa.Integer(), nullable=False),
        sa.Column("embedded_chunks", sa.Integer(), nullable=False),
        sa.Column("indexed_chunks", sa.Integer(), nullable=False),
        sa.Column("progress_percent", sa.Float(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["knowledge_base_id"], ["knowledge_bases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_indexing_jobs_document_id"), "indexing_jobs", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_indexing_jobs_knowledge_base_id"),
        "indexing_jobs",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_index(op.f("ix_indexing_jobs_status"), "indexing_jobs", ["status"], unique=False)
    op.add_column("users", sa.Column("admin_role", sa.String(length=50), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_users_admin_role"), "users", ["admin_role"], unique=False)

    # Safely migrate existing ADMIN accounts to MAIN_ADMIN role
    op.execute(
        "UPDATE users SET admin_role = 'MAIN_ADMIN' WHERE role = 'ADMIN' AND admin_role IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_admin_role"), table_name="users")
    op.drop_column("users", "permissions")
    op.drop_column("users", "admin_role")
    op.drop_index(op.f("ix_indexing_jobs_status"), table_name="indexing_jobs")
    op.drop_index(op.f("ix_indexing_jobs_knowledge_base_id"), table_name="indexing_jobs")
    op.drop_index(op.f("ix_indexing_jobs_document_id"), table_name="indexing_jobs")
    op.drop_table("indexing_jobs")
    # ### end Alembic commands ###
