"""add_kb_is_active_and_student_visible

Revision ID: aebbc63863c7
Revises: aab1529830b5
Create Date: 2026-10-07 15:00:00.654506

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aebbc63863c7'
down_revision: str | Sequence[str] | None = 'aab1529830b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('knowledge_bases', sa.Column('is_student_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_knowledge_bases_is_active'), 'knowledge_bases', ['is_active'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_is_student_visible'), 'knowledge_bases', ['is_student_visible'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_bases_is_student_visible'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_is_active'), table_name='knowledge_bases')
    op.drop_column('knowledge_bases', 'is_student_visible')
    op.drop_column('knowledge_bases', 'is_active')
    # ### end Alembic commands ###
